### ISSUE TITLE
Link invalid

### ISSUE THREAD

**Issue by Kogam22** [MLH/mlh-hackathon-flask-starter#12]
Step 4: Update environment variables and run the Server.

Create a new file named .env by duplicating .env.example. Update the new file with the GitHub credentials. It should look similar to this:

```
# .env file
DATABASE_URL="[INSERT_DATABASE_URL]"
GITHUB_CLIENT_ID="[INSERT_CLIENT_ID]"
GITHUB_CLIENT_SECRET="[INSERT_CLIENT_SECRET]"
```

You replace the GitHub credentials here and update the database URL. Learn more about the required **Environment Variables here**.

**Environment Variables here** is invalid

**Comment by nlaz** [comment]
Good catch @Kogam22 ! I updated the documentation to fix this link.
