### ISSUE TITLE
Application Error with Demo Link

### ISSUE THREAD

**Issue by nguyen-nhat** [MLH/mlh-hackathon-flask-starter#13]
https://hackathon-starter-python.herokuapp.com/

Error Message:
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
`heroku logs --tail`

![](https://i.imgur.com/0cFW8YP.png)

**Comment by nlaz** [comment]
Hey @nguyen-nhat thanks for catching the issue with the demo. We updated our service tier so it shouldn't be down anymore. Thanks again!
