### ISSUE TITLE
read me asks for Database URL config before establishing the database

### ISSUE THREAD

**Issue by rkrevolution** [MLH/mlh-hackathon-flask-starter#7]
We're prompted to create .env file w/ a database URL before having established the DB URL.

**Comment by fblampe** [comment]
I noticed the same thing, plus the link to the PostgreSQL installation instructions just points to a "What's New" page, which does not explain how to install it.

**Comment by rkrevolution** [comment]
http://www.postgresqltutorial.com/install-postgresql/
http://www.postgresqltutorial.com/connect-to-postgresql-database/

**Comment by ferdian26** [comment]
Check

**Comment by Nydhal** [comment]
You can use an in-memory database
DATABASE_URL="sqlite://"

**Comment by shafiemukhre** [comment]
Can someone give an example of postgreSQL url for the database?

**Comment by nlaz** [comment]
@shafiemukhre This is an example of the postgreSQL url I use for local development: 

```
DATABASE_URL="postgresql://localhost:5432/mlh-hackathon-starter-flask"
```

**Comment by nlaz** [comment]
I updated the documentation to include this feedback by clarifying the database step in the installation process. https://github.com/MLH/mlh-hackathon-flask-starter/commit/eb70e0bbae4dc82377fc78ddbbd0416ac8fa4dd9. Let me know if you have any other issues.
